# Generated by Django 3.2.8 on 2021-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('messege', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=350)),
                ('slug', models.CharField(default='', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('price_in', models.CharField(max_length=10)),
                ('area_sqft', models.IntegerField()),
                ('plot_or_house_or_flat', models.CharField(max_length=5)),
                ('floors', models.IntegerField(blank=True, default=1, null=True)),
                ('bedroom', models.IntegerField(blank=True)),
                ('bathroom', models.IntegerField(blank=True)),
                ('balcony', models.IntegerField(blank=True)),
                ('img1', models.ImageField(default='', upload_to='')),
                ('img2', models.ImageField(default='', upload_to='')),
                ('img3', models.ImageField(default='', upload_to='')),
                ('img4', models.ImageField(default='', upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
