# Generated by Django 3.2.8 on 2021-10-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('price_in', models.CharField(max_length=10)),
                ('area_sqft', models.IntegerField()),
                ('plot_or_house', models.CharField(max_length=5)),
                ('bedroom', models.IntegerField(blank=True)),
                ('bathroom', models.IntegerField(blank=True)),
                ('balcony', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
