# Generated by Django 3.2.8 on 2021-10-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='img1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='img2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='img3',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='img4',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
