# Generated by Django 3.2.8 on 2021-10-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_property_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='plot_or_house',
            new_name='plot_or_house_or_flat',
        ),
    ]
