# Generated by Django 3.2.8 on 2021-10-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_plot_or_house_property_plot_or_house_or_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=350),
        ),
    ]
