# Generated by Django 3.2.8 on 2021-11-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
