# Generated by Django 3.2.8 on 2021-12-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211105_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='allIps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ips', models.TextField(default=None)),
                ('postname', models.TextField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
