# Generated by Django 3.2.8 on 2023-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230430_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='img10',
        ),
        migrations.RemoveField(
            model_name='property',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='property',
            name='img7',
        ),
        migrations.RemoveField(
            model_name='property',
            name='img8',
        ),
        migrations.RemoveField(
            model_name='property',
            name='img9',
        ),
        migrations.AlterField(
            model_name='property',
            name='img1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='img2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='img3',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='img4',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
